name: ICRC POC - Build and upload

on:
  push:
    branches: [ ICRC-POC ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn clean package

      - uses: actions/upload-artifact@v2
        with:
          name: Package
          path: omod/target/appointments-1.2.3-ICRC-POC.omod
